export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as NFTokens } from './NFTokens'
export { default as FTokens } from './FTokens'
export { default as MyNFTokens } from './MyNFTokens'